### ISSUE TITLE
是否可以添加4.0API接口的切换服务？

### ISSUE THREAD

**Issue by 1666059026** [XHXJ/json-GPT-translator#1]
在我自身使用 网页版会员的情况下，觉得4.0的聪慧比3.5高出不少。

理论上使用4.0API的翻译效果会更好。

虽然仍然没有申请到4.0API接口，不过这应该是个很不错的提议。

当前使用3.5英译中，有些情况会不对等行，或者漏翻。

应该是出自于3.5自身的局限。

**Comment by XHXJ** [comment]
是的,当前解决gpt错行漏翻的问题最好的还是使用gpt4,后续考虑加入模型切换,这在代码层面是可以切换的,下一次版本我会把配置模型的选项开放出来.

**Comment by 1666059026** [comment]
> 是的,当前解决gpt错行漏翻的问题最好的还是使用gpt4,后续考虑加入模型切换,这在代码层面是可以切换的,下一次版本我会把配置模型的选项开放出来.

我之前也使用网页4.0 翻译过几次英文的游戏文本
在我实践中，有一个小细节，你在帮我按照**格式翻译这段话，需求在这句话话后面就会出现漏翻

如果你在帮我按照**格式翻译这段话，在下面换一行就不会出现

**

你可以注意一下这个细节
