### ISSUE TITLE
为什么是上传excel文件之后带翻译条数总是0

### ISSUE THREAD

**Issue by dddpeppapig** [XHXJ/json-GPT-translator#11]
我的excel文件格式是第一列是序号，第二列是中文，要把它翻译成日文

**Comment by XHXJ-mini** [comment]
不需要序号,第一列是原文,只会读取第一列的内容

**Comment by dddpeppapig** [comment]
是要同时上传json和excel吗， 我上传了之后还是识别不出来数据。是一定要用translaor++ 和Mtool导出的excel文件和json文件吗， 我自己手动创建的excel文件如何别识别呢？这是我尝试使用的excel和json文件[
[新建 Microsoft Excel 工作表.xlsx](https://github.com/XHXJ/json-GPT-translator/files/12509767/Microsoft.Excel.xlsx)
](url)

**Comment by XHXJ-mini** [comment]
是可以自定义自己想翻译的文件的,不过你需要在上传的时候自己再套一层zip文件就可以,我抽空改一下这个上传设置(最近太忙不一定动).
比如是这样
[Microsoft.Excel.zip](https://github.com/XHXJ/json-GPT-translator/files/12509856/Microsoft.Excel.zip)

**Comment by XHXJ-mini** [comment]
![image](https://github.com/XHXJ/json-GPT-translator/assets/131327532/4d70f247-0ab5-465a-935b-47b6b70141a3)
我随便测试了一下没啥问题

**Comment by dddpeppapig** [comment]
感谢回复，我自己是将excel文件压缩成zip压缩包上传，但一直上传失败，您的压缩包我上传是没有问题的不知道是不是我用的压缩软件的问题，这是我用我的显示上传失败的压缩包
[压缩包文件.excel.zip](https://github.com/XHXJ/json-GPT-translator/files/12511950/excel.zip)

**Comment by XHXJ** [comment]
在打包成zip包的文件中,文件名称不能为中文,可能是中文编码问题造出的,确保文件名为英文就正常了.

**Comment by dddpeppapig** [comment]
ok了感谢，已经成功导入了
