### ISSUE TITLE
运行测试时报错“系统异常”

### ISSUE THREAD

**Issue by dddpeppapig** [XHXJ/json-GPT-translator#12]
填入api host：https://api.caipacity.com，点击测试时候系统报错。log日志见下图。望解答
<img width="744" alt="企业微信截图_16944152591797" src="https://github.com/XHXJ/json-GPT-translator/assets/142002545/88b5575b-7e2f-4c94-83e7-95e5b933c636">

**Comment by XHXJ** [comment]
根目录有log目录,可否上传完整日志

**Comment by dddpeppapig** [comment]
[app.log](https://github.com/XHXJ/json-GPT-translator/files/12593934/app.log)
log日志如我上传所示

**Comment by lkaly** [comment]
我也遇到了相同的问题

**Comment by XHXJ** [comment]
> [app.log](https://github.com/XHXJ/json-GPT-translator/files/12593934/app.log) log日志如我上传所示

检查你的代理设置是否正常,能否正常访问openai的api.该报错是连接openai是返回的值无法转换成json格式报错的.
