### ISSUE TITLE
逐条翻译成本有点高了

### ISSUE THREAD

**Issue by Mnaisuka** [XHXJ/json-GPT-translator#13]
可以试试改用“gpt-3.5-turbo-instruct”，并且使用批量翻译，我测试了一下，成本是逐条翻译的几十分之一
`
chunked = ChunkedSubmit(list, 1200)
export = {}
for value in chunked:
    body = f"Translate to {tl or 'Chinese'}, save as JSON, with translation results as key-value pairs:" + \
        json.dumps(value)
    tokens = 4096 - get_token_count(body)
    complete = openai.Completion.create(
        model="gpt-3.5-turbo-instruct",
        prompt=body,
        max_tokens=tokens,
        temperature=0.2
    )
    print(complete)
    export.update(json.loads(complete['choices'][0]['text']))
return export
`

**Comment by XHXJ** [comment]
你说的是complete,然后有几个限制1.默认tokens是4096,有些小了.加上本身的提示词,和要翻译的内容,显得有些捉襟见肘.2.用的是complete接口.和现在聊天翻译逻辑有些许不一样.
如果你想加入该翻译逻辑可以自己在com.xhxj.jsongpttranslator.translation包下实现
