### ISSUE TITLE
系統異常

### ISSUE THREAD

**Issue by ant10202000** [XHXJ/json-GPT-translator#14]
我不知道我缺了什麼步驟

我無法正常使用他 我確實導入我的json

也輸入了我的API Key

但是開始翻譯後並沒有反應

而當我嘗試chagpt配置中的測試翻譯時 也總是出現系統異常

我少了什麼嗎?

**Comment by XHXJ** [comment]
请提供在目录下的log日志文件,我看看是怎么回事.
