### ISSUE TITLE
测试时出现了问题

### ISSUE THREAD

**Issue by SakuraHana01** [XHXJ/json-GPT-translator#16]
在openai key管理中添加了key，但是测试时收到了以下的报错
![屏幕截图 2024-01-20 173145](https://github.com/XHXJ/json-GPT-translator/assets/137737677/b7426b52-c7af-4c68-8078-aff4930f46a7)

![image](https://github.com/XHXJ/json-GPT-translator/assets/137737677/f16e9092-6e02-4bc2-8c9a-27a5f5da05b5)

api.openai.com返回的错误信息：
![屏幕截图 2024-01-20 172233](https://github.com/XHXJ/json-GPT-translator/assets/137737677/a3258498-1417-47a2-86ce-3b25494b647b)
请问该如何解决，十分感谢！！

**Comment by XHXJ** [comment]
openai更新了api接口,我项目中使用的是 [chatgpt-java](https://github.com/Grt1228/chatgpt-java) 调用框架,现在已升级成最新版本1.1.5,目前还没有打包更新版本.你拉取最新main分支代码在本地运行就可以了

**Comment by SakuraHana01** [comment]
> openai更新了api接口,我项目中使用的是 [chatgpt-java](https://github.com/Grt1228/chatgpt-java) 调用框架,现在已升级成最新版本1.1.5,目前还没有打包更新版本.你拉取最新main分支代码在本地运行就可以了



> openai更新了api接口,我项目中使用的是 [chatgpt-java](https://github.com/Grt1228/chatgpt-java) 调用框架,现在已升级成最新版本1.1.5,目前还没有打包更新版本.你拉取最新main分支代码在本地运行就可以了

非常感谢！！
