### ISSUE TITLE
【bug】当使用使用traslator++导出.xlsx文件有目录时识别不正确

### ISSUE THREAD

**Issue by meng010220** [XHXJ/json-GPT-translator#2]
**感谢开源:)**
描述一下我遇到的问题：
比如我在translator++导出一个带有目录结构的待翻译项目
```
DATA
└─BasicData
    └─DataBase.dat
        └─db
             └─28.xlsx
            


```
![img](https://img.imoeq.com/i/2023/05/23/image.png)
它把目录也当成带翻译的文件了，**而且导出的结果会失去该目录结构**
希望导出的结果能够保持原来的目录结构

以及文件名后缀现在翻译结果会自动加.xlsx。这样就变成了**28.xlsx.xlsx**

**Comment by XHXJ** [comment]
感谢反馈,下一个版本将会修改excel 导出文件命名问题,但是不会修改树形目录结构记录问题,因为导入设计初期没有添加记录目录结构的功能.添加这个功能太繁琐了,项目查询文件列表的展示也要一起改变为树形,感觉作用不大不准备加入了.

**Comment by XHXJ** [comment]
https://github.com/XHXJ/json-GPT-translator/commit/8b6e22cfa13f258ea0e044dc272de07427116bfd
