### ISSUE TITLE
希望加个一键复制原文到译文的功能

### ISSUE THREAD

**Issue by akatSS8** [XHXJ/json-GPT-translator#21]
有些Mtool读出来的代码部分，会反复试图翻译，一直消耗token，但就是翻不出结果。
如果停止翻译直接输出，它们又不在输出文件里
这些部分的内容往往又很长，一条条复制太花时间了，希望加个批量复制原文的按钮。

**Comment by XHXJ** [comment]
不理解你的意思...是在哪个页面上增加这个功能实现什么逻辑?...可以的话方便列出示例图么?
