### ISSUE TITLE
【bug】翻译translator++导出文件时由于“重名”导致的bug

### ISSUE THREAD

**Issue by meng010220** [XHXJ/json-GPT-translator#4]
[[https://github.com/XHXJ/json-GPT-translator/issues/2]()](https://github.com/XHXJ/json-GPT-translator/issues/2)
当时我在这个issue里提出想要保持原目录结构的问题，没有被采纳，可能没有表达清楚

其实导出文件没有目录结构会导致一个bug：
**就是如果打包翻译的压缩文件里有两个目录，这两个目录里有同一个名字的文件，现阶段导出的翻译结果，将会丢失其中一个文件**

举个例子

```
DATA
└─A
    └─1.xlsx
└─B
    └─1.xlsx
```
如果不保存原来的目录结构，那么这时输出结果只有一个1.xlsx文件

**Comment by XHXJ** [comment]
恩...如果遇到这样包含AB文件夹的项目可以直接分别导入成AB两个项目来翻译管理吗?如果引入结构保存功能会增加相当一部分的复杂的功能和逻辑,文件列表要记录树形结构,导出要按树形导出.如果还有许多人反馈需要这个功能我可以添加一下.
