### ISSUE TITLE
项目里删除了但是 翻译查询里还有 

### ISSUE THREAD

**Issue by lhj5426** [XHXJ/json-GPT-translator#5]
![image](https://github.com/XHXJ/json-GPT-translator/assets/30548000/f0edd201-74b5-4971-8ac6-3091307dfa03)
我刚翻译了一个项目 然后删除掉了 然后又导入一个项目
虽然项目里是一个 但是在翻译查询里 计数并没有被清零
之前是500多个翻译完删掉了
 然后又导入500多 
 正常情况下是不是项目删除了之后 查询里也是0?
 导入之后 查询里应该是重新开始计数吧？

 大佬这个是漏掉了忘删了吗
 现在是 导入一个项目 删掉在再导入一个项目 在翻译查询里的 编号是 累计叠加的而不是清零重新计数

**Comment by XHXJ** [comment]
你所看到的id只是该数据的唯一key表示,也就是id,总数显示:共526条,你删除了项目,又导入了项目,数量是正确的.
请不要依据你看到的id最后的编号判断总共还有多少句子.


这个涉及sql数据库自增列,默认删除的序号不会从0开始计数,而是沿用之前的序列继续自增,如果每次删除去判断id是否被使用,反而会很繁琐.关于id自增的相关使用网上可以找到很多例子.
其实这个点不用太去纠结它,因为它不影响使用.只要数据被删除就行了.
因为要实现被删除的id重复使用,每次插入新数据还需要去查询该数据id是否被分配,反而会影响性能.
而且正常的项目实际上都不会真实删除数据,而是将该数据打上isdelete标记,所以id还是存在的.虽然在该项目没有这么做而是实际删除了数据.
相关参考:
https://zhuanlan.zhihu.com/p/107947577
https://www.lsjlt.com/news/61999.html

**Comment by lhj5426** [comment]
> 你所看到的id只是该数据的唯一key表示,也就是id,总数显示:共526条,你删除了项目,又导入了项目,数量是正确的. 请不要依据你看到的id最后的编号判断总共还有多少句子.
> 
> 这个涉及sql数据库自增列,默认删除的序号不会从0开始计数,而是沿用之前的序列继续自增,如果每次删除去判断id是否被使用,反而会很繁琐.关于id自增的相关使用网上可以找到很多例子. 其实这个点不用太去纠结它,因为它不影响使用.只要数据被删除就行了. 因为要实现被删除的id重复使用,每次插入新数据还需要去查询该数据id是否被分配,反而会影响性能. 而且正常的项目实际上都不会真实删除数据,而是将该数据打上isdelete标记,所以id还是存在的.虽然在该项目没有这么做而是实际删除了数据. 相关参考: https://zhuanlan.zhihu.com/p/107947577 https://www.lsjlt.com/news/61999.html

我现在是每次删数据库然后重新清零来但是有一个问题 API还有代理 是跟着数据库走的 删了之后每次都要重新填写。。。
我不介意每次重新删数据库 重新统计 但是能不能 吧API和代理分离出来？
这叫强迫症

**Comment by XHXJ** [comment]
没事你不用每次都删除db/文件夹,id的序号不是你实际的数据库条数,总数要看左下角的总共xxx条.
API和代理是没有被持久化,没有被数据库记录的,你可以导出你的配置文件,然后每次使用的时候导入回去..

这个功能需求我记录一下,下周的版本添加,确实现在配置文件没有做持久化操作.每次关闭软件重新运行都会读取默认配置.下个版本改进.

**Comment by lhj5426** [comment]
> 没事你不用每次都删除db/文件夹,id的序号不是你实际的数据库条数,总数要看左下角的总共xxx条. API和代理是没有被持久化,没有被数据库记录的,你可以导出你的配置文件,然后每次使用的时候导入回去..
> 
> 这个功能需求我记录一下,下周的版本添加,确实现在配置文件没有做持久化操作.每次关闭软件重新运行都会读取默认配置.下个版本改进.

嗯 原来是这么回事
