### ISSUE TITLE
系统异常

### ISSUE THREAD

**Issue by lhj5426** [XHXJ/json-GPT-translator#6]
1.10 没事
 大佬刚发的 111 版 
 一直这
 
![image](https://github.com/XHXJ/json-GPT-translator/assets/30548000/a77a99e3-e793-4f89-9458-b11fabd16f67)

![image](https://github.com/XHXJ/json-GPT-translator/assets/30548000/da9b1a28-fe81-4a67-9907-6defb7d7ecc3)

**Comment by XHXJ** [comment]
这确实是一个bug,目前的办法是你先点击开始翻译后,再回去测试翻译.
下一版修复

**Comment by XHXJ** [comment]
[新增原文译文正则表达式查询,id查询,批量单条翻译](https://github.com/XHXJ/json-GPT-translator/commit/25b590a858f3bb40120e87df36b9dc94128ad10b#diff-869b1229e1b5eb6c36abb2577cc3d9beef5e3dee561ab1666a9dac9f7b51a2fbR158)
