### ISSUE TITLE
请问如何把请求频率降低

### ISSUE THREAD

**Issue by CatCars** [XHXJ/json-GPT-translator#7]
我在测试用Claude代替记不住命令的gpt3.5时遇到了问题。
请求频率实在是太快了，我点一下开始翻译，直接蹦出200多条对话，Claude禁不住这个频率请问如何降低请求频率.
![2](https://github.com/XHXJ/json-GPT-translator/assets/44657929/ccbe698f-4873-40db-b27e-df05e3f63f5a)
![1](https://github.com/XHXJ/json-GPT-translator/assets/44657929/31f48a57-06bc-4b75-a691-a4c29f37b079)

Claude倒是不容易忘设定，翻译水平也不算差。

**Comment by XHXJ** [comment]
你是自己编写了翻译代码吗?
你可以参考以下代码
[ChatGptTranslationServiceImpl.java](https://github.com/XHXJ/json-GPT-translator/blob/main/gpt-translator/src/main/java/com/xhxj/jsongpttranslator/service/chatgpt/ChatGptTranslationServiceImpl.java) 翻译开始的实现代码
[com.xhxj.jsongpttranslator.translation.TranslationModeSwitcher](https://github.com/XHXJ/json-GPT-translator/blob/25b590a858f3bb40120e87df36b9dc94128ad10b/gpt-translator/src/main/java/com/xhxj/jsongpttranslator/translation/TranslationModeSwitcher.java) 策略模式的实现

gpt-translator/src/main/java/com/xhxj/jsongpttranslator/translation/mode 你可以在这个包下新建你的翻译实现逻辑分别实现:

```
    /**
     * 批量翻译
     * @param data
     */
    void batchTranslate(List<TranslationData> data);

    void translateOne(List<TranslationData> data);

    /**
     * 停止翻译
     */
    void stopTranslate();
```

批量翻译的逻辑和单条翻译的逻辑,停止的可以不用写可以参考:
[com.xhxj.jsongpttranslator.translation.mode.ChatTranslationMode](https://github.com/XHXJ/json-GPT-translator/blob/52125988f5b31aee3e3aadddb6a6937110937a0f/gpt-translator/src/main/java/com/xhxj/jsongpttranslator/translation/async/chat/ChatGptTranslationAsyncServiceImpl.java) 类

如果你想限制每分钟调用速率请在你请求发送的地方使用:
```
            //限制每分钟的API调用
            apiLimiter.waitForApiCallAvailability(0);
```

如果你想修改翻译速率修改:
[ApiLimiter.java](https://github.com/XHXJ/json-GPT-translator/blob/25b590a858f3bb40120e87df36b9dc94128ad10b/gpt-translator/src/main/java/com/xhxj/jsongpttranslator/translation/ApiLimiter.java)
```
    private static int MAX_API_CALLS_PER_MINUTE = 3000; // 每分钟的API调用限制 (RPM)
    private static int MAX_TOKENS_PER_MINUTE = 300000; // 每分钟的令牌限制 (TPM)
    private static int MAX_REQUESTS_PER_SECOND = 2; // 每秒最大请求速率
```
