### ISSUE TITLE
无法保存Chat GPT配置

### ISSUE THREAD

**Issue by InCoree** [XHXJ/json-GPT-translator#8]
1.程序运行只能在国内ip环境
2.excel的话，只能用Translator++导出zip才行，自己压缩成zip无法上传
3.无法保存CHATgpt配置，显示系统异常

**Comment by InCoree** [comment]
![image](https://github.com/XHXJ/json-GPT-translator/assets/51859682/f1aabc81-c857-438a-8e8e-d31b2e6d14d0)

**Comment by InCoree** [comment]
大佬们求助

**Comment by XHXJ** [comment]
发一下程序运行路径下logs/的日志文件:

Translator++导出excel成文件夹后,用7z压缩软件压缩成zip,一般不会有什么问题(其他压缩软件因为压缩算法问题可能会导致软件无法解压)

代理如果是socks
示例:
地址:127.0.0.1
端口:7234
填写后保存,可以切换到测试页面测试翻译结果

**Comment by InCoree** [comment]
> 发一下程序运行路径下logs/的日志文件:
> 
> Translator++导出excel成文件夹后,用7z压缩软件压缩成zip,一般不会有什么问题(其他压缩软件因为压缩算法问题可能会导致软件无法解压)
> 
> 代理如果是socks 示例: 地址:127.0.0.1 端口:7234 填写后保存,可以切换到测试页面测试翻译结果

------------------
谢谢老哥，日志在家里的电脑上，上班没开远程不好操作，晚上我回去再试试
