### ISSUE TITLE
一点测试就系统异常

### ISSUE THREAD

**Issue by kklyhx** [XHXJ/json-GPT-translator#9]
一点测试就系统异常,求大佬打救我
<img width="1154" alt="2" src="https://github.com/XHXJ/json-GPT-translator/assets/137495578/84c2df60-c02b-4837-bcf3-b936c4fd65cf">
<img width="1357" alt="1" src="https://github.com/XHXJ/json-GPT-translator/assets/137495578/0dc47f17-a9c7-4ffe-92b4-17fbe8686f95">

**Comment by XHXJ** [comment]
检查你的api是否能正常使用,看错误信息可以得知你的api现在超额了..
